image: cboettig/labnotebook

script:
  - ls
  - pwd
  - git clone -b source https://github.com/cboettig/cboettig.github.io ../source
  - cd ../source && Rscript -e 'servr::jekyll(serve=FALSE)'
 


deploy:
  bash:
    script:
      - ./../cboettig.github.io/deploy.sh
     

